export const dummydata = [
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "10/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "59",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "17/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "19/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "21/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "58",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "22/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "56",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "24/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "26/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "28/02/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "14/03/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "125",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "15/03/2020",
    LengthOfStay: "1",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "486",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "17/03/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "23/03/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "Gastroenterology",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "299",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "30/04/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "02/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "IP_EL",
    TypeCat: "Inpatient",
    EventDate: "07/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Elective: Waiting List",
    Specialty: "Gastroenterology",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "451",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "18/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "57",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "19/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "76",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "22/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "60",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "24/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "26/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "54",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "29/05/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Accident & Emergency",
    Specialty: '"Ear, Nose & Throat"',
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "126",
  },
  {
    Type: "IP_EL",
    TypeCat: "Inpatient",
    EventDate: "02/06/2020",
    LengthOfStay: "10",
    AdmissionMethod: "Elective: Waiting List",
    Specialty: '"Ear, Nose & Throat"',
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "702",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "19/06/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "24/06/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "115",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "25/06/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "109",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "26/06/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Accident & Emergency",
    Specialty: "Trauma & Orthopaedics",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "150",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "01/07/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "10/07/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Accident & Emergency",
    Specialty: "Trauma & Orthopaedics",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "92",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "25/07/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "60",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "08/08/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "14/08/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Accident & Emergency",
    Specialty: "Trauma & Orthopaedics",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "88",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "30/08/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "18/09/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "30/09/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "109",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "30/09/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "1100",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "09/10/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Accident & Emergency",
    Specialty: "Trauma & Orthopaedics",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "78",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "06/11/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "16/11/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "117",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "11/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "140",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "11/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "479",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "13/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "124",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "13/12/2020",
    LengthOfStay: "2",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "435",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "17/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "22/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "79",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "22/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "438",
  },
  {
    Type: "RADIO",
    TypeCat: "Appointment",
    EventDate: "23/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "General Practitioner",
    Specialty: "General Medical Practice",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "51",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "29/12/2020",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "10/02/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "13/02/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "14/02/2021",
    LengthOfStay: "1",
    AdmissionMethod: "Emergency: GP",
    Specialty: "General Medicine",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "431",
  },
  {
    Type: "RADIO",
    TypeCat: "Appointment",
    EventDate: "04/03/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Out Patients",
    Specialty: "General Medicine",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "14/04/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "30/04/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "121",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "02/05/2021",
    LengthOfStay: "2",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "General Medicine",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "1060",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "04/05/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "Gastroenterology",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "82",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "04/05/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "146",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "05/05/2021",
    LengthOfStay: "1",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "225",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "17/05/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Consultant",
    Specialty: "Plastic Surgery",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "67",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "19/05/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "0",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "02/06/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "Gastroenterology",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "84",
  },
  {
    Type: "UCC",
    TypeCat: "Emergency",
    EventDate: "12/06/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Walk-In",
    Specialty: "Open Access",
    Provider: "Your local walk-in",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "0",
  },
  {
    Type: "OP",
    TypeCat: "Appointment",
    EventDate: "30/06/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "Gastroenterology",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "84",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "17/07/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Ambulance",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "77",
  },
  {
    Type: "AE",
    TypeCat: "Emergency",
    EventDate: "18/07/2021",
    LengthOfStay: "0",
    AdmissionMethod: "Other",
    Specialty: "A&E",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "Some extra information",
    TotalCost: "52",
  },
  {
    Type: "IP_NEL",
    TypeCat: "Inpatient",
    EventDate: "18/07/2021",
    LengthOfStay: "8",
    AdmissionMethod: "Emergency: A&E",
    Specialty: "Accident & Emergency",
    Provider: "Some Large NHS Acute Trust",
    Description1: "A description of the conditions and procedures",
    Description2: "",
    TotalCost: "241",
  },
];
