export const ConditionTypes = [
  {
    title: "Asthma",
    icon: "far fa-inhaler",
    value: "asthma",
    default: true,
  },
  {
    title: "COPD",
    icon: "far fa-lungs",
    value: "copd",
    default: true,
  },
  {
    title: "Late COPD (Shielded)",
    icon: "fas fa-lungs",
    value: "late_copd",
    default: true,
    color: "warn",
  },
  {
    title: "CHD",
    icon: "fas fa-heart-circle",
    value: "chd",
    default: true,
  },
  {
    title: "Heart Failure",
    icon: "fas fa-heart-broken",
    value: "heart_failure",
    default: true,
  },
  {
    title: "Atrial Fibrillation",
    icon: "fas fa-heart-rate",
    value: "atrial_fibrillation",
    default: true,
  },
  {
    title: "PAD",
    icon: "fas fa-bacon",
    value: "pad",
    default: true,
  },
  {
    title: "Stroke TIA",
    icon: "fas fa-head-side-brain",
    value: "stroke_tia",
    default: true,
  },
  {
    title: "Cancer",
    icon: "fas fa-ribbon",
    value: "cancer",
    default: true,
  },
  {
    title: "Chemo Radiotherapy (Shielded)",
    icon: "fas fa-syringe",
    value: "chemo_radiotherapy",
    default: true,
    color: "warn",
  },
  {
    title: "Haematological Cancers (Shielded)",
    icon: "far fa-ribbon",
    value: "haematological_cancers",
    default: true,
    color: "warn",
  },
  {
    title: "Depression",
    icon: "far fa-sad-tear",
    value: "depression",
    default: true,
  },
  {
    title: "Dementia",
    icon: "fas fa-mind-share",
    value: "dementia",
    default: true,
  },
  {
    title: "Mental Health",
    icon: "fas fa-head-side-medical",
    value: "mental_health",
    default: true,
  },
  {
    title: "Psychotic Disorder",
    icon: "far fa-head-side-medical",
    value: "psychotic_disorder_flag",
    default: true,
  },
  {
    title: "Learning Disabilities",
    icon: "far fa-book-medical",
    value: "learning_disabilities",
    default: true,
  },
  {
    title: "Diabetes",
    icon: "fad fa-syringe",
    value: "diabetes",
    default: true,
  },
  {
    title: "Hypothyroid",
    icon: "fal fa-walking",
    value: "hypothyroid",
    default: true,
  },
  {
    title: "Chronic Kidney Disease",
    icon: "fas fa-kidneys",
    value: "ckd",
    default: true,
  },
  {
    title: "Epilepsy",
    icon: "fas fa-brain",
    value: "epilepsy",
    default: true,
  },
  {
    title: "Osteoporosis",
    icon: "fas fa-bone-break",
    value: "osteoporosis",
    default: true,
  },
  {
    title: "Rheumatoid Arthritis",
    icon: "fad fa-skeleton",
    value: "rheumatoid_arthritis",
    default: true,
  },
  {
    title: "Smoker",
    icon: "fas fa-smoking",
    value: "smoker",
    default: true,
  },
  {
    title: "Substance Misuse",
    icon: "fas fa-bong",
    value: "substance_misuse",
    default: true,
  },
  {
    title: "Dispensing",
    icon: "fas fa-prescription",
    value: "dispensing_flag",
    default: true,
  },
  {
    title: "Pregnant with Congenital Heart Defect (Shielded)",
    icon: "pregnant_woman",
    value: "pregnant_with_congenital_heart_defect",
    default: true,
    color: "warn",
  },
  {
    title: "Transplant (Shielded)",
    icon: "fas fa-hands-heart",
    value: "transplant",
    default: true,
    color: "warn",
  },
  {
    title: "Palliative Care",
    icon: "fas fa-procedures",
    value: "palliative_care_flag",
    default: true,
  },
  {
    title: "Rare Diseases (Shielded)",
    icon: "fas fa-books-medical",
    value: "rare_diseases",
    default: true,
    color: "warn",
  },
];
